// RECIPE LIBRARY - EASY TO UPDATE
// To change any recipe in the future, refer to it by number or id (e.g. "update recipe #4" or "update recipe-7").
// Ingredient rows use numeric quantity + unit so lists and groceries can be scaled (meal.scale × household × quantity).
// Planned: align scale with user profile (calorie goal, macros, household size, servings).
// Recipes are grouped: Breakfast → Lunch → Dinner → Snack; alphabetically by name within each group.

import type { Recipe, RecipeVariationDetail } from "@/types";
import {
  eggBiteVariationDetails,
  highProteinOvernightOats,
  highProteinSmoothie,
} from "@/recipes/enhancedBreakfastRecipes";

const sheetPanChickenVariations: RecipeVariationDetail[] = [
  {
    id: "mixed-veg",
    label: "Mixed Veg",
    ingredients: [
      { name: "Broccoli florets", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Bell pepper (chunks)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Red onion (wedges)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Potato (cubed)", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Carrot (thick slices)", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Garlic powder", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Smoked paprika", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Fresh parsley", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Toss vegetables with olive oil, garlic powder, paprika, salt, and pepper on the sheet pan.",
      "Nestle chicken among the vegetables; roast 22–28 minutes until chicken reaches 165°F and vegetables are tender.",
      "Rest chicken 3 minutes, garnish with parsley, and serve from the pan.",
    ],
    servingWeightGrams: 515,
  },
  {
    id: "honey-garlic-potatoes",
    label: "Honey Garlic + Potatoes",
    ingredients: [
      { name: "Broccoli florets", quantity: 2, unit: "cups", category: "Produce" },
      { name: "Baby red potatoes (halved)", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Garlic", quantity: 2, unit: "cloves", category: "Produce" },
      { name: "Soy sauce (low-sodium)", quantity: 1.5, unit: "tbsp", category: "Pantry" },
      { name: "Honey", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Fresh parsley (optional)", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Whisk soy sauce, honey, minced garlic, and olive oil for the glaze.",
      "Toss potatoes with half the glaze on the sheet pan; roast 12 minutes.",
      "Add chicken and broccoli; toss with remaining glaze and roast 16–18 minutes until chicken is cooked through.",
      "Rest 3 minutes, garnish with parsley, and serve from the pan.",
    ],
    servingWeightGrams: 520,
  },
  {
    id: "honey-garlic-rice",
    label: "Honey Garlic + Rice",
    ingredients: [
      { name: "Broccoli florets", quantity: 2, unit: "cups", category: "Produce" },
      { name: "Garlic", quantity: 2, unit: "cloves", category: "Produce" },
      { name: "Soy sauce (low-sodium)", quantity: 1.5, unit: "tbsp", category: "Pantry" },
      { name: "Honey", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Cooked white rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Fresh parsley (optional)", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Whisk soy sauce, honey, minced garlic, and olive oil for the glaze.",
      "Toss chicken and broccoli with the glaze on a sheet pan; roast 18–22 minutes until chicken is cooked through.",
      "Warm rice if needed. Rest chicken 3 minutes, slice, and serve over rice with pan juices.",
      "Garnish with parsley if desired.",
    ],
    servingWeightGrams: 505,
    calories: 575,
    protein: 45,
    carbs: 62,
    fat: 16,
  },
  {
    id: "greek-rice",
    label: "Greek + Rice",
    ingredients: [
      { name: "Zucchini", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Bell pepper", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Red onion", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Olive oil (for vegetables)", quantity: 0.5, unit: "tbsp", category: "Pantry" },
      { name: "Dried oregano", quantity: 1, unit: "tsp", category: "Spices" },
      { name: "Cooked white rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Lemon", quantity: 0.5, unit: "pcs", category: "Produce" },
    ],
    instructions: [
      "Toss chicken and chopped vegetables with remaining olive oil and oregano on the sheet pan.",
      "Roast 22–28 minutes until chicken reaches 165°F.",
      "Serve over warm rice with a squeeze of lemon.",
    ],
    servingWeightGrams: 530,
    calories: 595,
    protein: 48,
    carbs: 58,
    fat: 18,
  },
  {
    id: "greek-orzo",
    label: "Greek Orzo",
    ingredients: [
      { name: "Orzo (dry)", quantity: 2, unit: "oz", category: "Grains" },
      { name: "Cherry tomatoes (halved)", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Zucchini (chunked)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Bell pepper (chunked)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Kalamata olives (pitted, halved)", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Garlic", quantity: 2, unit: "cloves", category: "Produce" },
      { name: "Dried oregano", quantity: 1, unit: "tsp", category: "Spices" },
      { name: "Feta cheese (crumbled)", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Lemon", quantity: 0.5, unit: "pcs", category: "Produce" },
    ],
    instructions: [
      "Cook orzo in salted boiling water until just al dente, 7–8 minutes; drain well.",
      "Toss zucchini, bell pepper, tomatoes, olives, and minced garlic with half the olive oil, oregano, salt, and pepper on the sheet pan.",
      "Nestle chicken among the vegetables; roast 18–22 minutes at 425°F until chicken reaches 165°F.",
      "Scatter cooked orzo around the pan for the last 5 minutes to warm through and pick up pan juices.",
      "Crumble feta over everything, squeeze lemon on top, and serve from the pan.",
    ],
    servingWeightGrams: 545,
    calories: 645,
    protein: 48,
    carbs: 68,
    fat: 22,
  },
  {
    id: "mediterranean",
    label: "Mediterranean",
    ingredients: [
      { name: "Cherry tomatoes (halved)", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Kalamata olives (pitted)", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Red onion (thick wedges)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Feta cheese (crumbled)", quantity: 3, unit: "tbsp", category: "Dairy" },
      { name: "Dried oregano", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Fresh parsley", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Toss cherry tomatoes, olives, and red onion wedges with olive oil, oregano, salt, and pepper on the sheet pan.",
      "Place chicken on the pan and nestle it among the vegetables.",
      "Roast 20–24 minutes at 425°F until chicken reaches 165°F and tomatoes are blistered.",
      "Crumble feta over the pan during the last 3 minutes; rest chicken 3 minutes.",
      "Finish with parsley and serve directly from the sheet pan.",
    ],
    servingWeightGrams: 525,
    calories: 585,
    protein: 47,
    carbs: 46,
    fat: 24,
  },
  {
    id: "french-onion",
    label: "French Onion",
    ingredients: [
      { name: "Yellow onion (thinly sliced)", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Garlic", quantity: 2, unit: "cloves", category: "Produce" },
      { name: "Beef broth or chicken broth", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Shredded mozzarella or Gruyère", quantity: 0.25, unit: "cup", category: "Dairy" },
      { name: "Fresh thyme (optional)", quantity: 0.5, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Toss sliced onions and minced garlic with olive oil, salt, and pepper; spread on the sheet pan.",
      "Roast onions alone 10 minutes at 425°F until starting to soften and brown.",
      "Push onions to the edges, add chicken to the center, and drizzle broth over the onions.",
      "Roast 16–20 minutes more until chicken reaches 165°F and onions are deeply golden.",
      "Top chicken and onions with cheese during the last 3–4 minutes until melted; rest 3 minutes before serving.",
    ],
    servingWeightGrams: 530,
    calories: 615,
    protein: 49,
    carbs: 50,
    fat: 24,
  },
  {
    id: "baked-crack",
    label: "Baked Crack",
    ingredients: [
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
      { name: "Light cream cheese", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Shredded cheddar", quantity: 0.25, unit: "cup", category: "Dairy" },
      { name: "Ranch seasoning mix", quantity: 1, unit: "tsp", category: "Spices" },
      { name: "Broccoli florets", quantity: 1.5, unit: "cups", category: "Produce" },
    ],
    instructions: [
      "Lay bacon on the sheet pan and roast 8–10 minutes at 425°F until crisp; crumble and set aside.",
      "Toss broccoli with a little olive oil, salt, and pepper on the same pan.",
      "Mix cream cheese, ranch seasoning, and half the cheddar in a small bowl.",
      "Place chicken on the pan, spread the cream cheese mixture over each piece, and roast 18–22 minutes until chicken reaches 165°F.",
      "Top with remaining cheddar and crumbled bacon during the last 3 minutes; rest 3 minutes and serve.",
    ],
    servingWeightGrams: 540,
    calories: 685,
    protein: 52,
    carbs: 48,
    fat: 32,
  },
  {
    id: "greek-tzatziki",
    label: "Greek + Tzatziki",
    ingredients: [
      { name: "Cherry tomatoes (halved)", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Cucumber (chunked)", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Bell pepper (chunked)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Red onion (wedges)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Dried oregano", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Tzatziki", quantity: 3, unit: "tbsp", category: "Dairy" },
      { name: "Lemon", quantity: 0.5, unit: "pcs", category: "Produce" },
    ],
    instructions: [
      "Toss tomatoes, cucumber, bell pepper, and onion with olive oil, oregano, salt, and pepper on the sheet pan.",
      "Nestle chicken among the vegetables; roast 20–24 minutes at 425°F until chicken reaches 165°F.",
      "Rest chicken 3 minutes, then serve over the vegetables with tzatziki spooned on top or on the side.",
      "Finish with a squeeze of lemon.",
    ],
    servingWeightGrams: 535,
    calories: 580,
    protein: 47,
    carbs: 46,
    fat: 19,
  },
];

const rotisserieMealPrepVariations: RecipeVariationDetail[] = [
  {
    id: "broccoli-carrots",
    label: "Broccoli + Carrots",
    ingredients: [
      { name: "Broccoli florets", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Carrot coins", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Soy sauce or teriyaki", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Sesame seeds", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Fresh herbs (parsley or cilantro)", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Roast broccoli and carrots with olive oil, salt, and pepper at 425°F (220°C) for 18–22 minutes.",
      "Pack rice, shredded chicken, and vegetables into containers.",
      "Pack sauce separately; drizzle before eating and top with sesame seeds and herbs.",
    ],
    servingWeightGrams: 480,
  },
  {
    id: "sweet-potato-greens",
    label: "Sweet Potato + Greens",
    ingredients: [
      { name: "Sweet potato", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Green vegetable mix", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Salsa verde (optional)", quantity: 2, unit: "tbsp", category: "Pantry" },
    ],
    instructions: [
      "Roast cubed sweet potato and green vegetables at 425°F (220°C) for 22–28 minutes.",
      "Pack rice, shredded chicken, and roasted vegetables into containers.",
      "Add salsa verde just before eating if using.",
    ],
    servingWeightGrams: 495,
    calories: 520,
    protein: 42,
    carbs: 45,
    fat: 17,
  },
];

const searedChickenThighVariations: RecipeVariationDetail[] = [
  {
    id: "carrots-brussels-sprouts",
    label: "Carrots + Brussels Sprouts",
    ingredients: [
      { name: "Carrots (thick batons)", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Brussels sprouts (halved)", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Yellow onion (wedges)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Fresh parsley", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Toss carrots, Brussels sprouts, and onion with half the olive oil, salt, and pepper on a sheet pan.",
      "Roast 20–25 minutes, flipping vegetables once, until browned and tender.",
      "Sear thighs using the base pan method while vegetables roast.",
      "Rest chicken 3–5 minutes, garnish with parsley, and serve over the roasted vegetables.",
    ],
    servingWeightGrams: 505,
  },
  {
    id: "broccoli-potatoes",
    label: "Broccoli + Potatoes",
    ingredients: [
      { name: "Baby red potatoes (halved)", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Broccoli florets", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Garlic", quantity: 2, unit: "cloves", category: "Produce" },
      { name: "Lemon", quantity: 0.5, unit: "pcs", category: "Produce" },
    ],
    instructions: [
      "Toss potatoes with half the olive oil, salt, pepper, and minced garlic; roast 15 minutes.",
      "Sear thighs using the base pan method while potatoes roast.",
      "Add broccoli to the sheet pan with remaining oil; roast 12–15 minutes until tender.",
      "Rest chicken 3–5 minutes, squeeze lemon over everything, and serve.",
    ],
    servingWeightGrams: 510,
  },
  {
    id: "peppers-zucchini",
    label: "Peppers + Zucchini",
    ingredients: [
      { name: "Bell pepper (chunks)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Zucchini (half-moons)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Red onion (wedges)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Dried oregano", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Lemon", quantity: 0.5, unit: "pcs", category: "Produce" },
    ],
    instructions: [
      "Toss peppers, zucchini, and onion with half the olive oil, oregano, salt, and pepper on a sheet pan.",
      "Roast 18–22 minutes until softened and lightly charred.",
      "Sear thighs using the base pan method while vegetables roast.",
      "Rest chicken 3–5 minutes, squeeze lemon over the plate, and serve.",
    ],
    servingWeightGrams: 495,
    calories: 540,
    protein: 41,
    carbs: 28,
    fat: 29,
  },
  {
    id: "greek-tzatziki",
    label: "Greek + Tzatziki",
    ingredients: [
      { name: "Cherry tomatoes (halved)", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Cucumber (chunked)", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Bell pepper (chunks)", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Red onion (wedges)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Dried oregano", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Tzatziki", quantity: 3, unit: "tbsp", category: "Dairy" },
      { name: "Lemon", quantity: 0.5, unit: "pcs", category: "Produce" },
    ],
    instructions: [
      "Toss tomatoes, cucumber, bell pepper, and onion with half the olive oil, oregano, salt, and pepper on a sheet pan.",
      "Roast 18–22 minutes until vegetables are softened and lightly charred.",
      "Sear thighs using the base pan method while vegetables roast.",
      "Rest chicken 3–5 minutes, then serve over the vegetables with tzatziki on top or on the side.",
      "Squeeze lemon over the plate before eating.",
    ],
    servingWeightGrams: 520,
    calories: 595,
    protein: 43,
    carbs: 30,
    fat: 32,
  },
];

const turkeyHummusWrapVariations: RecipeVariationDetail[] = [
  {
    id: "carrots-greens",
    label: "Carrots + Greens",
    ingredients: [
      { name: "Shredded carrots", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Mixed greens or spinach", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Red onion (optional)", quantity: 2, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Layer shredded carrots and greens over the turkey.",
      "Add onion if using; roll tightly and slice in half on the diagonal.",
    ],
    servingWeightGrams: 385,
  },
  {
    id: "cucumber-tomato",
    label: "Cucumber + Tomato",
    ingredients: [
      { name: "Cucumber (sliced)", quantity: 0.33, unit: "cup", category: "Produce" },
      { name: "Cherry tomatoes (halved)", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Fresh dill or parsley (optional)", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Layer cucumber and tomatoes over the turkey.",
      "Top with herbs if using; roll tightly and slice in half.",
    ],
    servingWeightGrams: 380,
    calories: 470,
    protein: 42,
    carbs: 36,
    fat: 16,
  },
  {
    id: "peppers-spinach",
    label: "Peppers + Spinach",
    ingredients: [
      { name: "Bell pepper strips", quantity: 0.33, unit: "cup", category: "Produce" },
      { name: "Baby spinach", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Squeeze of lemon (optional)", quantity: 1, unit: "tsp", category: "Produce" },
    ],
    instructions: [
      "Layer pepper strips and spinach over the turkey.",
      "Add a squeeze of lemon if desired; roll tightly and slice in half.",
    ],
    servingWeightGrams: 375,
    calories: 465,
    protein: 42,
    carbs: 35,
    fat: 16,
  },
];

const omeletteVariations: RecipeVariationDetail[] = [
  {
    id: "ham-tomato",
    label: "Ham + Tomato",
    ingredients: [
      { name: "Diced ham", quantity: 2, unit: "oz", category: "Protein" },
      { name: "Diced tomato", quantity: 0.25, unit: "cup", category: "Produce" },
      { name: "Fresh tomato slices (optional)", quantity: 2, unit: "slices", category: "Produce" },
      { name: "Fresh parsley (optional)", quantity: 1, unit: "tsp", category: "Produce" },
    ],
    instructions: [
      "Warm ham and tomato in the pan 1 minute before adding eggs, or fold into the omelette as it sets.",
      "Serve with tomato slices and parsley on the side if using.",
    ],
    servingWeightGrams: 320,
  },
  {
    id: "spinach-cheese",
    label: "Spinach + Cheese",
    ingredients: [
      { name: "Baby spinach", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Shredded cheddar or mozzarella", quantity: 2, unit: "tbsp", category: "Dairy" },
    ],
    instructions: [
      "Wilt spinach in the pan briefly before pouring in eggs.",
      "Add cheese when the omelette is nearly set; fold and melt 30 seconds.",
    ],
    servingWeightGrams: 310,
    calories: 370,
    protein: 28,
    carbs: 4,
    fat: 26,
  },
  {
    id: "mushroom-peppers",
    label: "Mushroom + Peppers",
    ingredients: [
      { name: "Sliced mushrooms", quantity: 0.33, unit: "cup", category: "Produce" },
      { name: "Diced bell pepper", quantity: 0.25, unit: "cup", category: "Produce" },
      { name: "Shredded cheese (optional)", quantity: 1, unit: "tbsp", category: "Dairy" },
    ],
    instructions: [
      "Sauté mushrooms and peppers 2–3 minutes until softened before adding eggs.",
      "Fold in cheese when the omelette is nearly set if using.",
    ],
    servingWeightGrams: 315,
    calories: 355,
    protein: 26,
    carbs: 6,
    fat: 24,
  },
];

const frittataVariations: RecipeVariationDetail[] = [
  {
    id: "spinach-tomato",
    label: "Spinach + Tomato",
    ingredients: [
      { name: "Baby spinach", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Cherry tomatoes (halved)", quantity: 0.25, unit: "cup", category: "Produce" },
    ],
    instructions: [
      "Sauté spinach and tomatoes in the skillet 1–2 minutes until spinach wilts.",
      "Pour egg mixture over vegetables and continue with the base stovetop and oven steps.",
    ],
    servingWeightGrams: 240,
  },
  {
    id: "bacon-feta-tomato",
    label: "Bacon + Feta + Tomato",
    ingredients: [
      { name: "Cooked bacon (crumbled)", quantity: 1, unit: "slice", category: "Protein" },
      { name: "Cherry tomatoes (halved)", quantity: 0.25, unit: "cup", category: "Produce" },
      { name: "Crumbled feta", quantity: 1, unit: "tbsp", category: "Dairy" },
      { name: "Fresh parsley (optional)", quantity: 1, unit: "tsp", category: "Produce" },
    ],
    instructions: [
      "Warm tomatoes and bacon in the skillet 1 minute.",
      "Pour in egg mixture; top with feta and parsley before the oven finish.",
    ],
    servingWeightGrams: 255,
    calories: 340,
    protein: 33,
    carbs: 6,
    fat: 20,
  },
  {
    id: "mushroom-onion",
    label: "Mushroom + Onion",
    ingredients: [
      { name: "Sliced mushrooms", quantity: 0.33, unit: "cup", category: "Produce" },
      { name: "Diced onion", quantity: 2, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Sauté onion and mushrooms 3–4 minutes until softened and lightly browned.",
      "Pour egg mixture over and continue with the base stovetop and oven steps.",
    ],
    servingWeightGrams: 245,
    calories: 275,
    protein: 29,
    carbs: 7,
    fat: 16,
  },
  {
    id: "turkey-peppers",
    label: "Turkey + Peppers",
    ingredients: [
      { name: "Diced turkey breast or deli turkey", quantity: 2, unit: "oz", category: "Protein" },
      { name: "Diced bell pepper", quantity: 0.25, unit: "cup", category: "Produce" },
      { name: "Dried Italian herbs", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Sauté pepper and turkey with Italian herbs 2 minutes until warmed through.",
      "Pour egg mixture over and continue with the base stovetop and oven steps.",
    ],
    servingWeightGrams: 250,
    calories: 310,
    protein: 36,
    carbs: 6,
    fat: 15,
  },
];

const sirloinBreakfastPlatterVariations: RecipeVariationDetail[] = [
  {
    id: "hash-browns-tomatoes",
    label: "Hash Browns + Tomatoes",
    ingredients: [
      { name: "Shredded hash browns (cooked)", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Shredded cheddar (optional)", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", category: "Produce" },
    ],
    instructions: [
      "Cook hash browns in a skillet with a little oil until golden; melt cheddar on top if using.",
      "Warm cherry tomatoes in the same pan 1–2 minutes until slightly softened.",
      "Plate hash browns and tomatoes alongside the steak, eggs, and mushrooms.",
    ],
    servingWeightGrams: 620,
  },
  {
    id: "croissant-tomatoes",
    label: "Croissant + Tomatoes",
    ingredients: [
      { name: "Croissant", quantity: 1, unit: "medium", category: "Grains" },
      { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", category: "Produce" },
    ],
    instructions: [
      "Skip the hash browns — warm the croissant in the oven or toaster 3–4 minutes until flaky.",
      "Sauté cherry tomatoes 1–2 minutes until softened.",
      "Plate the croissant and tomatoes alongside the steak, eggs, and mushrooms.",
    ],
    servingWeightGrams: 580,
    calories: 820,
    protein: 52,
    carbs: 48,
    fat: 48,
  },
];

const breakfastTacoVariations: RecipeVariationDetail[] = [
  {
    id: "pork-bacon-flour",
    label: "Pork Bacon + Flour Tortilla",
    ingredients: [
      { name: "10-inch flour tortilla", quantity: 1, unit: "large", category: "Grains" },
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
    ],
    instructions: [
      "Cook bacon in a skillet over medium until crisp; crumble or leave whole and set aside.",
      "Warm the flour tortilla in the dry skillet 30 seconds per side until soft with light char spots.",
      "Fill with scrambled eggs and bacon; fold and serve.",
    ],
    servingWeightGrams: 285,
  },
  {
    id: "turkey-bacon-flour",
    label: "Turkey Bacon + Flour Tortilla",
    ingredients: [
      { name: "10-inch flour tortilla", quantity: 1, unit: "large", category: "Grains" },
      { name: "Turkey bacon", quantity: 3, unit: "slices", category: "Protein" },
    ],
    instructions: [
      "Cook turkey bacon until crisp (usually 2–3 minutes per side).",
      "Warm the flour tortilla and fill with eggs and turkey bacon as in the classic build.",
    ],
    servingWeightGrams: 280,
    calories: 405,
    protein: 26,
    carbs: 36,
    fat: 16,
  },
  {
    id: "pork-bacon-corn",
    label: "Pork Bacon + Corn Tortilla",
    ingredients: [
      { name: "6-inch corn tortillas", quantity: 2, unit: "small", category: "Grains" },
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
    ],
    instructions: [
      "Use two corn tortillas instead of one flour tortilla — about 120 fewer calories than the flour base.",
      "Warm corn tortillas briefly on a dry skillet; stack or serve as two smaller tacos with eggs and bacon divided between them.",
    ],
    servingWeightGrams: 265,
    calories: 310,
    protein: 24,
    carbs: 22,
    fat: 17,
  },
  {
    id: "loaded-toppings",
    label: "Loaded Toppings",
    ingredients: [
      { name: "10-inch flour tortilla", quantity: 1, unit: "large", category: "Grains" },
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
      { name: "Shredded cheddar", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Avocado (sliced)", quantity: 0.25, unit: "medium", category: "Produce" },
      { name: "Salsa", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Sour cream (optional)", quantity: 1, unit: "tbsp", category: "Dairy" },
      { name: "Hot sauce (optional)", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Fresh cilantro", quantity: 1, unit: "tbsp", category: "Produce" },
      { name: "Jalapeño slices (optional)", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Build the classic bacon-and-egg taco, then top with cheese, avocado, and salsa while the eggs are still warm.",
      "Finish with cilantro, and add sour cream, hot sauce, or jalapeños to taste.",
    ],
    servingWeightGrams: 340,
    calories: 555,
    protein: 28,
    carbs: 42,
    fat: 32,
  },
];

const breakfastSandwichVariations: RecipeVariationDetail[] = [
  {
    id: "center-cut-bread",
    label: "Center-Cut Bacon + Sliced Bread",
    ingredients: [
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
      { name: "Sliced bread (toasted)", quantity: 2, unit: "slices", category: "Grains" },
    ],
    instructions: [
      "Cook bacon until crisp; toast bread in a buttered skillet until golden.",
      "Stack fried eggs, bacon, and melted cheese between the toast slices.",
    ],
    servingWeightGrams: 295,
  },
  {
    id: "center-cut-bagel",
    label: "Center-Cut Bacon + Bagel",
    ingredients: [
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
      { name: "Plain bagel (halved, toasted)", quantity: 1, unit: "medium", category: "Grains" },
    ],
    instructions: [
      "Cook bacon until crisp; toast the halved bagel until golden.",
      "Build the sandwich on the bagel halves with eggs, bacon, and cheese.",
    ],
    servingWeightGrams: 320,
    calories: 605,
    protein: 28,
    carbs: 54,
    fat: 26,
  },
  {
    id: "center-cut-biscuit",
    label: "Center-Cut Bacon + Biscuit",
    ingredients: [
      { name: "Center-cut bacon", quantity: 2, unit: "slices", category: "Protein" },
      { name: "Breakfast biscuit", quantity: 1, unit: "large", category: "Grains" },
    ],
    instructions: [
      "Cook bacon until crisp; split and lightly toast the biscuit.",
      "Layer eggs, bacon, and cheese inside the biscuit.",
    ],
    servingWeightGrams: 285,
    calories: 515,
    protein: 32,
    carbs: 32,
    fat: 33,
  },
  {
    id: "turkey-bacon-bread",
    label: "Turkey Bacon + Sliced Bread",
    ingredients: [
      { name: "Turkey bacon", quantity: 3, unit: "slices", category: "Protein" },
      { name: "Sliced bread (toasted)", quantity: 2, unit: "slices", category: "Grains" },
    ],
    instructions: [
      "Cook turkey bacon until crisp; toast bread in a buttered skillet.",
      "Stack eggs, turkey bacon, and cheese between the toast slices.",
    ],
    servingWeightGrams: 290,
    calories: 495,
    protein: 31,
    carbs: 30,
    fat: 25,
  },
  {
    id: "turkey-bacon-bagel",
    label: "Turkey Bacon + Bagel",
    ingredients: [
      { name: "Turkey bacon", quantity: 3, unit: "slices", category: "Protein" },
      { name: "Plain bagel (halved, toasted)", quantity: 1, unit: "medium", category: "Grains" },
    ],
    instructions: [
      "Cook turkey bacon until crisp; toast the halved bagel.",
      "Build the sandwich on the bagel with eggs, turkey bacon, and cheese.",
    ],
    servingWeightGrams: 315,
    calories: 625,
    protein: 31,
    carbs: 54,
    fat: 25,
  },
  {
    id: "turkey-bacon-biscuit",
    label: "Turkey Bacon + Biscuit",
    ingredients: [
      { name: "Turkey bacon", quantity: 3, unit: "slices", category: "Protein" },
      { name: "Breakfast biscuit", quantity: 1, unit: "large", category: "Grains" },
    ],
    instructions: [
      "Cook turkey bacon until crisp; split and lightly toast the biscuit.",
      "Layer eggs, turkey bacon, and cheese inside the biscuit.",
    ],
    servingWeightGrams: 280,
    calories: 535,
    protein: 35,
    carbs: 32,
    fat: 32,
  },
];

const eggHamToastVariations: RecipeVariationDetail[] = [
  {
    id: "base",
    label: "Eggs, Ham, Toast",
    ingredients: [],
    instructions: [
      "Toast the bread until golden.",
      "Heat olive oil in a nonstick skillet over medium heat.",
      "Cook eggs to preference (fried or scrambled) — use whole eggs, not grams.",
      "Warm deli ham in the same pan briefly.",
      "Serve eggs and ham over or beside the toast. Season with salt and pepper.",
    ],
    servingWeightGrams: 280,
  },
  {
    id: "avocado",
    label: "Eggs, Ham, Toast & Avocado",
    ingredients: [
      { name: "Avocado (sliced)", quantity: 0.25, unit: "medium", category: "Produce" },
    ],
    instructions: [
      "Toast the bread until golden.",
      "Heat olive oil in a nonstick skillet over medium heat.",
      "Cook eggs to preference (fried or scrambled) — use whole eggs, not grams.",
      "Warm deli ham in the same pan briefly.",
      "Serve eggs and ham over or beside the toast with sliced avocado on the side or on the toast.",
      "Season with salt and pepper.",
    ],
    servingWeightGrams: 330,
    calories: 385,
    protein: 24,
    carbs: 21,
    fat: 25,
  },
];

const bakedMeatballVariations: RecipeVariationDetail[] = [
  {
    id: "chicken",
    label: "Ground Chicken",
    ingredients: [{ name: "Ground chicken", quantity: 6, unit: "oz", category: "Protein" }],
    instructions: [
      "Mix ground chicken with parmesan, herbs, garlic, salt, and pepper until just combined — do not overwork.",
      "Roll into 5–6 equal meatballs (about 1.5 inches each).",
    ],
    servingWeightGrams: 485,
  },
  {
    id: "turkey",
    label: "Ground Turkey",
    ingredients: [{ name: "Lean ground turkey", quantity: 6, unit: "oz", category: "Protein" }],
    instructions: [
      "Mix lean ground turkey with parmesan, herbs, garlic, salt, and pepper until just combined.",
      "Roll into 5–6 equal meatballs; turkey can be slightly drier — avoid over-mixing.",
    ],
    servingWeightGrams: 485,
    calories: 525,
    protein: 43,
    carbs: 48,
    fat: 17,
  },
  {
    id: "beef",
    label: "Lean Ground Beef (93%)",
    ingredients: [{ name: "Lean ground beef (93%)", quantity: 6, unit: "oz", category: "Protein" }],
    instructions: [
      "Mix lean ground beef with parmesan, herbs, garlic, salt, and pepper until just combined.",
      "Roll into 5–6 equal meatballs; beef will brown more deeply when baked.",
    ],
    servingWeightGrams: 485,
    calories: 585,
    protein: 43,
    carbs: 48,
    fat: 24,
  },
];

export const recipeLibrary: Recipe[] = [
  // Breakfast
  {
    id: "blended-cottage-cheese-pudding-49",
    number: 1,
    name: "Cottage Cheese Pudding",
    imageUrl: "/recipes/cottage-cheese-pudding.png",
    cuisine: "american",
    tags: ["high_protein", "meal_prep", "breakfast_friendly", "quick"],
    mealSlots: ["breakfast", "snack"],
    calories: 310,
    protein: 38,
    carbs: 18,
    fat: 8,
    prepMinutes: 8,
    cookMinutes: 0,
    ingredients: [
      { name: "Cottage cheese", quantity: 1, unit: "cup", category: "Dairy" },
      { name: "Chocolate protein powder", quantity: 0.5, unit: "scoop", category: "Pantry" },
      { name: "Unsweetened cocoa powder", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Sweetener (to taste)", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Unsweetened almond milk", quantity: 0.25, unit: "cup", category: "Pantry" },
      { name: "Raspberries (for topping)", quantity: 0.5, unit: "cup", category: "Produce" }
    ],
    instructions: [
      "Add cottage cheese, protein powder, cocoa, sweetener, and almond milk to a blender.",
      "Blend until completely smooth; taste and adjust sweetness or liquid.",
      "Refrigerate until chilled if desired; top with raspberries before serving.",
      "Note: Rich, mousse-like dessert-for-breakfast. Secretly high-protein.",
    ],
    servingWeightGrams: 340,
  },
  {
    id: "cottage-cheese-egg-scramble-bowl-01",
    number: 2,
    name: "Cottage Cheese Egg Scramble Bowl",
    imageUrl: "/recipes/cottage-cheese-egg-scramble.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "breakfast_friendly"],
    mealSlots: ["breakfast", "snack"],
    calories: 385,
    protein: 32,
    carbs: 18,
    fat: 20,
    prepMinutes: 8,
    cookMinutes: 8,
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "large", category: "Protein" },
      { name: "Cottage cheese (low-fat)", quantity: 0.5, unit: "cup", category: "Dairy" },
      { name: "Baby spinach", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Olive oil", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" }
    ],
    instructions: [
      "Whisk eggs with a pinch of pepper.",
      "Heat oil in a pan; wilt spinach and halved tomatoes briefly.",
      "Pour in eggs and scramble until softly set.",
      "Fold in cottage cheese off heat and serve in a bowl."
    ],
  },
  {
    id: "egg-turkey-muffins-14",
    number: 3,
    name: "Egg and Turkey Muffins",
    imageUrl: "/recipes/egg-and-turkey-muffins.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "batch_friendly", "meal_prep"],
    mealSlots: ["breakfast", "lunch"],
    calories: 390,
    protein: 35,
    carbs: 8,
    fat: 23,
    prepMinutes: 12,
    cookMinutes: 22,
    ingredients: [
      { name: "Eggs", quantity: 3, unit: "large", category: "Protein" },
      { name: "Chopped turkey", quantity: 3, unit: "oz", category: "Protein" },
      { name: "Shredded cheese", quantity: 0.25, unit: "cup", category: "Dairy" },
      { name: "Mushrooms (optional)", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Bell peppers (optional)", quantity: 0.5, unit: "cup", category: "Produce" }
    ],
    instructions: [
      "Mix eggs with chopped turkey, cheese, and optional veggies.",
      "Pour into muffin tin.",
      "Bake until set.",
      "Cool and store in fridge."
    ],
  },
  {
    id: "greek-yogurt-berry-protein-bowl-with-oats-05",
    number: 4,
    name: "Greek Yogurt and Berries Protein Bowl",
    imageUrl: "/recipes/greek-yogurt-and-berries-protein-bowl.png",
    cuisine: "mediterranean",
    tags: ["whole_food", "high_protein", "quick", "meal_prep"],
    mealSlots: ["breakfast", "snack"],
    calories: 395,
    protein: 28,
    carbs: 48,
    fat: 10,
    prepMinutes: 6,
    cookMinutes: 0,
    ingredients: [
      { name: "Plain Greek yogurt", quantity: 1, unit: "cup", category: "Dairy" },
      { name: "Rolled oats", quantity: 0.33, unit: "cup", category: "Grains" },
      { name: "Mixed berries", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Chia seeds", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Honey", quantity: 1, unit: "tsp", category: "Pantry" }
    ],
    instructions: [
      "Add yogurt to a bowl.",
      "Top with oats, berries, and chia seeds.",
      "Drizzle honey if desired and serve."
    ],
  },
  {
    id: "greek-yogurt-parfait-51",
    number: 5,
    name: "Greek Yogurt Parfait",
    imageUrl: "/recipes/greek-yogurt-parfait.png",
    cuisine: "mediterranean",
    tags: ["whole_food", "high_protein", "meal_prep", "breakfast_friendly", "quick"],
    mealSlots: ["breakfast", "snack"],
    calories: 445,
    protein: 32,
    carbs: 48,
    fat: 16,
    prepMinutes: 6,
    cookMinutes: 0,
    ingredients: [
      { name: "Plain Greek yogurt (0% or low sugar)", quantity: 1, unit: "cup", category: "Dairy" },
      { name: "High-protein granola (low sugar)", quantity: 0.33, unit: "cup", category: "Grains" },
      { name: "Fresh fruit (berries or sliced fruit)", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Peanut butter", quantity: 1, unit: "tbsp", category: "Pantry" },
    ],
    instructions: [
      "Choose plain Greek yogurt labeled 0% or low sugar (check label — aim for ≤5 g sugar per cup).",
      "Layer yogurt, granola, and fruit in a jar or bowl.",
      "Drizzle or dollop peanut butter on top.",
      "Seal and refrigerate if meal prepping.",
      "Note: Extremely quick, no-cook high-protein breakfast. Perfect for meal prep.",
    ],
  },
  {
    id: "high-protein-egg-bites-53",
    number: 6,
    name: "High Protein Egg Bites",
    imageUrl: "/recipes/high-protein-egg-bites.png",
    cuisine: "american",
    tags: ["high_protein", "meal_prep", "batch_friendly", "breakfast_friendly", "quick"],
    mealSlots: ["breakfast", "snack"],
    calories: 220,
    protein: 20,
    carbs: 4,
    fat: 14,
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      { name: "Eggs", quantity: 4, unit: "large", category: "Protein" },
      { name: "Liquid egg whites", quantity: 0.5, unit: "cup", category: "Protein" },
      { name: "Cottage cheese", quantity: 0.25, unit: "cup", category: "Dairy" },
      { name: "Shredded cheese", quantity: 0.25, unit: "cup", category: "Dairy" },
    ],
    instructions: [
      "Heat oven to 325°F (165°C).",
      "Blend or whisk eggs, egg whites, cottage cheese, and shredded cheese until smooth.",
      "Select a variation below — add its ingredients and follow its steps.",
      "Pour into a greased muffin tin (silicone works well).",
      "Bake 20–25 minutes until puffed and set; cool and store or freeze.",
      "Note: Grab-and-go high-protein breakfast. Freezer-friendly and customizable.",
    ],
    variationDetails: eggBiteVariationDetails,
    mealPrepNotes: "Refrigerate up to 4 days or freeze up to 2 months. Reheat 30–45 seconds in microwave.",
  },
  highProteinOvernightOats,
  highProteinSmoothie,
  {
    id: "omelette-ham-tomato-56",
    number: 30,
    name: "Omelette",
    imageUrl: "/recipes/omelette.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "breakfast_friendly"],
    mealSlots: ["breakfast", "snack"],
    calories: 385,
    protein: 30,
    carbs: 5,
    fat: 26,
    prepMinutes: 5,
    cookMinutes: 8,
    servingWeightGrams: 320,
    ingredients: [
      { name: "Eggs", quantity: 3, unit: "large", category: "Protein" },
      { name: "Olive oil or butter", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Whisk eggs with salt and pepper until combined.",
      "Heat a nonstick skillet over medium. Add oil or butter and swirl to coat.",
      "Pour in eggs; let set 20–30 seconds, then gently push cooked edges toward the center.",
      "When the top is still slightly wet, add your chosen variation fillings on one half.",
      "Fold the omelette in half, cook 1 minute more, and slide onto a plate.",
    ],
    variationDetails: omeletteVariations,
    mealPrepNotes:
      "Best fresh. For meal prep, cook fully and refrigerate up to 2 days; reheat 30–45 seconds in microwave.",
  },
  {
    id: "cottage-cheese-frittata-57",
    number: 31,
    name: "Frittata",
    imageUrl: "/recipes/frittata.png",
    cuisine: "american",
    tags: ["high_protein", "meal_prep", "batch_friendly", "breakfast_friendly"],
    mealSlots: ["breakfast", "lunch", "snack"],
    calories: 265,
    protein: 28,
    carbs: 5,
    fat: 14,
    prepMinutes: 10,
    cookMinutes: 20,
    servingWeightGrams: 240,
    batchWeightGrams: 960,
    mealPrepBatchServings: 4,
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "large", category: "Protein" },
      { name: "Low-fat cottage cheese", quantity: 0.25, unit: "cup", category: "Dairy" },
      { name: "Olive oil", quantity: 0.5, unit: "tsp", category: "Pantry" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Heat oven to 375°F (190°C). Whisk eggs, cottage cheese, salt, and pepper until smooth — small cottage cheese curds are fine.",
      "Choose a variation below and prep those ingredients.",
      "For one serving: use a small (6–8 inch) oven-safe skillet. For 4 servings: multiply all ingredients ×4 and use a 10-inch skillet.",
      "Warm oil in the skillet over medium heat. Sauté variation ingredients per its steps.",
      "Pour in the egg mixture. Cook on the stovetop 2–3 minutes until edges look set.",
      "Transfer to the oven and bake 12–15 minutes until the center is just set (no jiggle when you shake the pan).",
      "Rest 5 minutes, then slice into wedges. One wedge = one serving.",
    ],
    variationDetails: frittataVariations,
    mealPrepNotes:
      "Keeps 4 days refrigerated in an airtight container. Reheat one wedge 45–60 seconds in the microwave, or 8 minutes at 350°F (175°C) in the oven for a firmer texture. Freezes up to 1 month; thaw overnight in the fridge before reheating.",
  },
  {
    id: "sirloin-breakfast-platter-58",
    number: 32,
    name: "Sirloin Breakfast Platter",
    imageUrl: "/recipes/sirloin-breakfast-platter.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "breakfast_friendly"],
    mealSlots: ["breakfast"],
    calories: 750,
    protein: 54,
    carbs: 38,
    fat: 42,
    prepMinutes: 12,
    cookMinutes: 25,
    servingWeightGrams: 620,
    ingredients: [
      { name: "Sirloin steak", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Eggs", quantity: 2, unit: "large", category: "Protein" },
      { name: "Sliced mushrooms", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Olive oil", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Butter", quantity: 1, unit: "tsp", category: "Dairy" },
      { name: "Salt", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Fresh parsley (optional)", quantity: 1, unit: "tbsp", category: "Produce" },
    ],
    instructions: [
      "Pat steak dry and season with salt and pepper. Choose a variation below for your potato or croissant and tomatoes.",
      "Heat a large skillet over high heat with half the oil. Sear steak 3–4 minutes per side for medium; rest 5 minutes, then slice.",
      "In the same pan over medium heat, sauté mushrooms with remaining oil until golden, 4–5 minutes. Season lightly and set aside.",
      "Reduce heat to medium-low. Melt butter and cook eggs sunny-side up (or over easy) 2–3 minutes until whites are set.",
      "Prepare variation sides per the steps below.",
      "Plate like a restaurant platter: sliced steak, eggs, mushrooms, and your chosen variation. Finish with parsley and cracked pepper.",
    ],
    variationDetails: sirloinBreakfastPlatterVariations,
    mealPrepNotes:
      "Best served immediately. Leftovers keep 2 days refrigerated — reheat steak and mushrooms in a skillet over medium, eggs 30 seconds in the microwave, and hash browns or croissant in the oven or toaster.",
  },
  {
    id: "breakfast-taco-59",
    number: 33,
    name: "Breakfast Taco",
    imageUrl: "/recipes/breakfast-taco.png",
    cuisine: "mexican",
    tags: ["whole_food", "high_protein", "quick", "breakfast_friendly"],
    mealSlots: ["breakfast", "snack"],
    calories: 430,
    protein: 24,
    carbs: 36,
    fat: 21,
    prepMinutes: 5,
    cookMinutes: 12,
    servingWeightGrams: 285,
    cookStyle: "assembled",
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "large", category: "Protein" },
      { name: "Butter or oil", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Choose a variation below for your tortilla, bacon type, and any toppings.",
      "Whisk eggs with salt and pepper. Melt butter in a skillet over medium-low and scramble gently until soft and fluffy — do not overcook.",
      "Cook bacon per your variation; warm the tortilla in the same skillet until pliable.",
      "Layer bacon and eggs down the center of the tortilla. Add toppings if using the loaded variation.",
      "Fold the sides in and roll into a burrito-style wrap, or serve open-faced restaurant-style.",
    ],
    variationDetails: breakfastTacoVariations,
    mealPrepNotes:
      "Best eaten fresh. Assembled tacos keep 1 day refrigerated — store tortilla separately if possible and reheat eggs and bacon before wrapping.",
  },
  {
    id: "breakfast-sandwich-60",
    number: 34,
    name: "Breakfast Sandwich",
    imageUrl: "/recipes/breakfast-sandwich.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "breakfast_friendly"],
    mealSlots: ["breakfast", "snack"],
    calories: 475,
    protein: 28,
    carbs: 30,
    fat: 26,
    prepMinutes: 5,
    cookMinutes: 12,
    servingWeightGrams: 295,
    cookStyle: "assembled",
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "large", category: "Protein" },
      { name: "Sliced cheddar or American cheese", quantity: 1, unit: "slice", category: "Dairy" },
      { name: "Butter", quantity: 1, unit: "tsp", category: "Dairy" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Choose a variation below for your bacon type and bread, bagel, or biscuit.",
      "Cook bacon per your variation until crisp; set aside and keep warm.",
      "Melt butter in the same skillet over medium. Fry eggs to your liking (over easy or over medium works well for a restaurant-style sandwich).",
      "Place cheese on the eggs during the last minute so it melts.",
      "Toast or warm your bread, bagel, or biscuit per the variation.",
      "Stack eggs and bacon on the bottom half, close the sandwich, and serve immediately.",
      "Note: This is a higher-calorie breakfast option. It may affect macro distribution or portion sizes for lunch and dinner.",
    ],
    variationDetails: breakfastSandwichVariations,
    mealPrepNotes:
      "Best eaten fresh. If meal prepping, store bacon and eggs separately from bread; assemble and toast after reheating.",
  },
  {
    id: "b-egg-ham-toast",
    number: 35,
    name: "Eggs, Ham, Toast",
    imageUrl: "/recipes/eggs-ham-toast.jpg",
    cuisine: "american",
    tags: ["whole_food", "quick", "high_protein"],
    mealSlots: ["breakfast", "snack"],
    calories: 305,
    protein: 23,
    carbs: 17,
    fat: 18,
    prepMinutes: 3,
    cookMinutes: 8,
    servingWeightGrams: 280,
    cookStyle: "assembled",
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "large", category: "Protein" },
      { name: "Deli ham (lean)", quantity: 2, unit: "slices", category: "Protein" },
      { name: "Bread (for toast)", quantity: 1, unit: "slice", category: "Grains" },
      { name: "Olive oil", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Choose a variation below — the base build is selected by default.",
      "Follow the variation steps for toasting, cooking eggs in olive oil, and warming the ham.",
      "Use whole eggs (not gram weights) so portions stay practical in the grocery list.",
    ],
    variationDetails: eggHamToastVariations,
    mealPrepNotes:
      "Best eaten fresh. Toast and eggs do not reheat well together — cook eggs and toast just before serving.",
  },
  // Lunch
  {
    id: "baked-chicken-meatballs-rice-veg-21",
    number: 7,
    name: "Baked Chicken Meatballs + Veggies + Rice",
    imageUrl: "/recipes/baked-chicken-meatballs-veggies-rice.png",
    cuisine: "italian",
    tags: ["whole_food", "high_protein", "meal_prep", "batch_friendly", "meal_prep_friendly"],
    mealSlots: ["lunch", "dinner"],
    calories: 530,
    protein: 43,
    carbs: 48,
    fat: 18,
    prepMinutes: 15,
    cookMinutes: 22,
    servingWeightGrams: 485,
    batchWeightGrams: 1940,
    mealPrepBatchServings: 4,
    ingredients: [
      { name: "Italian herbs", quantity: 1, unit: "tsp", category: "Spices" },
      { name: "Parmesan", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Garlic", quantity: 1, unit: "clove", category: "Produce" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Cooked rice", quantity: 0.75, unit: "cup", category: "Grains" },
      { name: "Roasted vegetables", quantity: 1, unit: "cup", category: "Produce" },
    ],
    instructions: [
      "Choose a meatball protein variation below (chicken, turkey, or lean beef).",
      "Heat oven to 425°F (220°C). Line a baking sheet with parchment.",
      "Follow your variation to mix and shape the meatballs; arrange on the sheet with space between each.",
      "Bake 18–22 minutes until browned and 165°F (74°C) in the center.",
      "While meatballs bake, cook rice and roast vegetables on a second sheet pan (or steam frozen vegetables for speed).",
      "Plate rice, vegetables, and meatballs together, or divide evenly into meal-prep containers.",
      "Recommended meal prep: multiply all ingredients ×4 for a 4-container batch — cook once, eat across the week.",
    ],
    variationDetails: bakedMeatballVariations,
    mealPrepNotes:
      "Recommended prep dish. Cook a full 4-portion batch — divide rice, roasted vegetables, and meatballs into containers. Refrigerate up to 4 days; reheat to 165°F. Meatballs freeze well up to 2 months; thaw overnight before reheating.",
  },
  {
    id: "beef-broccoli-stir-fry-bowl-with-white-rice-07",
    number: 8,
    name: "Beef & Broccoli Stir-Fry Bowl with White Rice",
    imageUrl: "/recipes/beef-broccoli-stir-fry.png",
    cuisine: "asian",
    tags: ["whole_food", "high_protein", "quick", "meal_prep"],
    mealSlots: ["lunch", "dinner"],
    calories: 545,
    protein: 36,
    carbs: 54,
    fat: 20,
    prepMinutes: 12,
    cookMinutes: 12,
    ingredients: [
      { name: "Lean beef strips", quantity: 170, unit: "g", category: "Protein" },
      { name: "Broccoli", quantity: 2, unit: "cups", category: "Produce" },
      { name: "Ginger (fresh)", quantity: 1, unit: "tsp", category: "Produce" },
      { name: "Soy sauce (low-sodium)", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Cornstarch", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Cooked white rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Avocado oil", quantity: 1, unit: "tbsp", category: "Pantry" }
    ],
    instructions: [
      "Toss beef with 1 tsp cornstarch and 1 tbsp soy sauce.",
      "Stir-fry beef in hot oil until browned; remove.",
      "Cook broccoli and ginger; return beef with remaining soy sauce.",
      "Serve over rice."
    ],
  },
  {
    id: "beef-veggie-stir-fry-17",
    number: 9,
    name: "Beef and Veggie Stir Fry",
    imageUrl: "/recipes/beef-veggie-stir-fry.png",
    cuisine: "asian",
    tags: ["whole_food", "high_protein", "quick", "meal_prep"],
    mealSlots: ["lunch", "dinner"],
    calories: 535,
    protein: 40,
    carbs: 42,
    fat: 22,
    prepMinutes: 12,
    cookMinutes: 12,
    ingredients: [
      { name: "Lean beef strips", quantity: 5, unit: "oz", category: "Protein" },
      { name: "Frozen mixed vegetables", quantity: 2, unit: "cups", category: "Produce" },
      { name: "Cooked rice", quantity: 0.75, unit: "cup", category: "Grains" },
      { name: "Simple stir-fry sauce", quantity: 1.5, unit: "tbsp", category: "Pantry" }
    ],
    instructions: [
      "Stir-fry beef until cooked.",
      "Add frozen vegetables.",
      "Add sauce and cook briefly.",
      "Serve over rice."
    ],
  },
  {
    id: "broccoli-chicken-casserole-pasta-42",
    number: 10,
    name: "Broccoli Chicken Casserole Pasta",
    imageUrl: "/recipes/broccoli-chicken-casserole-pasta.png",
    cuisine: "american",
    tags: ["high_protein", "meal_prep", "batch_friendly", "comfort"],
    mealSlots: ["lunch", "dinner"],
    calories: 610,
    protein: 44,
    carbs: 62,
    fat: 20,
    prepMinutes: 20,
    cookMinutes: 30,
    ingredients: [
      { name: "Cooked chicken breast", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Protein pasta (dry)", quantity: 2.5, unit: "oz", category: "Grains" },
      { name: "Broccoli florets", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Light cream cheese", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Shredded cheddar", quantity: 0.25, unit: "cup", category: "Dairy" },
      { name: "Chicken broth", quantity: 0.5, unit: "cup", category: "Pantry" }
    ],
    instructions: [
      "Cook pasta and steam broccoli until tender-crisp.",
      "Mix cooked pasta, chicken, broccoli, cream cheese, broth, and half the cheddar.",
      "Transfer to baking dish, top with remaining cheddar, and bake until bubbly."
    ],
  },
  {
    id: "chicken-burrito-bowl-11",
    number: 11,
    name: "Chicken Burrito Bowl",
    imageUrl: "/recipes/chicken-burrito-bowl.png",
    cuisine: "mexican",
    tags: ["whole_food", "high_protein", "meal_prep", "quick"],
    mealSlots: ["lunch"],
    calories: 540,
    protein: 47,
    carbs: 56,
    fat: 14,
    prepMinutes: 10,
    cookMinutes: 8,
    ingredients: [
      { name: "Cooked chicken breast", quantity: 5, unit: "oz", category: "Protein" },
      { name: "Black beans", quantity: 0.5, unit: "cup", category: "Pantry" },
      { name: "Microwave rice (cooked)", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Salsa", quantity: 0.25, unit: "cup", category: "Pantry" },
      { name: "Shredded lettuce", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Greek yogurt (optional)", quantity: 2, unit: "tbsp", category: "Dairy" }
    ],
    instructions: [
      "Warm chicken and black beans.",
      "Heat rice.",
      "Assemble bowl with rice base, chicken, beans, salsa, and greens.",
      "Add Greek yogurt if desired."
    ],
  },
  {
    id: "chicken-caesar-salad-extra-chicken-light-dressing-13",
    number: 12,
    name: "Chicken Caesar Salad",
    imageUrl: "/recipes/chicken-caesar-salad.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "meal_prep", "quick"],
    mealSlots: ["lunch", "dinner"],
    calories: 460,
    protein: 47,
    carbs: 20,
    fat: 20,
    prepMinutes: 12,
    cookMinutes: 0,
    ingredients: [
      { name: "Cooked chicken breast", quantity: 5, unit: "oz", category: "Protein" },
      { name: "Romaine lettuce", quantity: 2, unit: "cups", category: "Produce" },
      { name: "Parmesan", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Light Caesar dressing", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Croutons", quantity: 0.25, unit: "cup", category: "Grains" }
    ],
    instructions: [
      "Chop romaine and add to container.",
      "Top with sliced chicken, parmesan, and tomatoes.",
      "Pack dressing and croutons separately.",
      "Combine just before eating."
    ],
  },
  {
    id: "garlic-butter-chicken-bites-with-rice-37",
    number: 13,
    name: "Garlic Butter Chicken Bites + Rice",
    imageUrl: "/recipes/garlic-butter-chicken-bites-rice.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "meal_prep"],
    mealSlots: ["lunch", "dinner"],
    calories: 555,
    protein: 44,
    carbs: 52,
    fat: 18,
    prepMinutes: 12,
    cookMinutes: 12,
    ingredients: [
      { name: "Chicken breast (cubed)", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Cooked white rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Garlic", quantity: 2, unit: "cloves", category: "Produce" },
      { name: "Butter", quantity: 1, unit: "tbsp", category: "Dairy" },
      { name: "Parsley", quantity: 1, unit: "tbsp", category: "Produce" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" }
    ],
    instructions: [
      "Season and saute chicken bites until cooked through.",
      "Add butter and minced garlic; toss 1–2 minutes until fragrant.",
      "Finish with parsley and serve over warm rice."
    ],
  },
  {
    id: "greek-chicken-bowls-41",
    number: 14,
    name: "Greek Chicken Bowl",
    imageUrl: "/recipes/greek-chicken-bowl.png",
    cuisine: "mediterranean",
    tags: ["whole_food", "high_protein", "meal_prep"],
    mealSlots: ["lunch", "dinner"],
    calories: 565,
    protein: 46,
    carbs: 54,
    fat: 17,
    prepMinutes: 15,
    cookMinutes: 15,
    ingredients: [
      { name: "Cooked chicken breast", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Cooked rice or quinoa", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Cucumber", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Cherry tomatoes", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Feta", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Tzatziki", quantity: 2, unit: "tbsp", category: "Dairy" }
    ],
    instructions: [
      "Add rice or quinoa to a bowl.",
      "Top with chicken, cucumber, tomatoes, and feta.",
      "Serve with tzatziki on top or on the side."
    ],
  },
  {
    id: "ground-turkey-sweet-potato-skillet-04",
    number: 15,
    name: "Ground Turkey Sweet Potato Skillet",
    imageUrl: "/recipes/ground-turkey-sweet-potato-skillet.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "batch_friendly"],
    mealSlots: ["lunch", "dinner"],
    calories: 485,
    protein: 38,
    carbs: 42,
    fat: 18,
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      { name: "Lean ground turkey", quantity: 170, unit: "g", category: "Protein" },
      { name: "Sweet potato (diced)", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Onion", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Bell pepper", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Olive oil", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Smoked paprika", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" }
    ],
    instructions: [
      "Brown turkey in a large skillet with oil; season with paprika and salt.",
      "Add onion and sweet potato; cover and cook until tender, stirring occasionally.",
      "Stir in bell pepper; cook 3–4 minutes until crisp-tender.",
      "Choose a variation below — add melted cheese if you like (macros update automatically).",
    ],
    variationDetails: [
      {
        id: "classic",
        label: "Classic (no cheese)",
        ingredients: [],
        instructions: ["Serve hot from the skillet."],
      },
      {
        id: "with-cheese",
        label: "With melted cheese",
        ingredients: [
          { name: "Shredded cheddar or mozzarella", quantity: 0.25, unit: "cup", category: "Dairy" },
        ],
        instructions: [
          "Off heat, sprinkle cheese evenly over the skillet.",
          "Cover 1–2 minutes until melted, then serve.",
        ],
        calories: 585,
        protein: 45,
        carbs: 43,
        fat: 26,
      },
    ],
  },
  {
    id: "orange-chicken-rice-bowl-38",
    number: 16,
    name: "Orange Chicken Rice Bowl",
    imageUrl: "/recipes/orange-chicken-rice-bowl.png",
    cuisine: "asian",
    tags: ["high_protein", "meal_prep", "quick"],
    mealSlots: ["lunch", "dinner"],
    calories: 575,
    protein: 43,
    carbs: 66,
    fat: 14,
    prepMinutes: 12,
    cookMinutes: 14,
    ingredients: [
      { name: "Chicken breast", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Cooked rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Orange marmalade", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Soy sauce (low-sodium)", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Rice vinegar", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Steamed broccoli", quantity: 1, unit: "cup", category: "Produce" }
    ],
    instructions: [
      "Cook chicken pieces in a skillet until browned and cooked through.",
      "Whisk marmalade, soy sauce, and rice vinegar; add to pan and simmer until glazed.",
      "Serve orange chicken over rice with broccoli."
    ],
  },
  {
    id: "protein-packed-sushi-bowl-33",
    number: 17,
    name: "High-Protein Sushi Bowl",
    imageUrl: "/recipes/high-protein-sushi-bowl.png",
    cuisine: "japanese",
    tags: ["whole_food", "high_protein", "meal_prep", "quick"],
    mealSlots: ["lunch", "dinner"],
    calories: 560,
    protein: 40,
    carbs: 57,
    fat: 18,
    prepMinutes: 12,
    cookMinutes: 0,
    ingredients: [
      { name: "Cooked salmon or tuna", quantity: 5, unit: "oz", category: "Protein" },
      { name: "Cooked rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Cucumber", quantity: 0.75, unit: "cup", category: "Produce" },
      { name: "Soy sauce", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Spicy mayo or yogurt sauce", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Seaweed snacks", quantity: 1, unit: "pack", category: "Pantry" }
    ],
    instructions: [
      "Combine rice with salmon or tuna and cucumber.",
      "Drizzle with soy sauce and spicy mayo.",
      "Add crumbled seaweed right before eating."
    ],
  },
  {
    id: "rotisserie-chicken-sweet-potato-meal-prep-16",
    number: 18,
    name: "Rotisserie Chicken + Veg + Rice Meal Prep",
    imageUrl: "/recipes/rotisserie-chicken-veg-rice-meal-prep.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "meal_prep", "batch_friendly", "quick"],
    mealSlots: ["lunch", "dinner"],
    calories: 535,
    protein: 42,
    carbs: 50,
    fat: 14,
    prepMinutes: 12,
    cookMinutes: 22,
    servingWeightGrams: 480,
    mealPrepBatchServings: 4,
    ingredients: [
      { name: "Rotisserie chicken (shredded)", quantity: 5, unit: "oz", category: "Protein" },
      { name: "Cooked white rice", quantity: 0.75, unit: "cup", category: "Grains" },
      { name: "Olive oil", quantity: 1, unit: "tsp", category: "Pantry" },
    ],
    instructions: [
      "Shred rotisserie chicken and cook rice if needed (or use microwave rice).",
      "Choose a vegetable variation below and roast or prep accordingly.",
      "Divide rice, chicken, and vegetables evenly among meal-prep containers.",
      "Store sauce or salsa separately when noted; refrigerate up to 4 days.",
    ],
    variationDetails: rotisserieMealPrepVariations,
    mealPrepNotes:
      "Keeps 4 days refrigerated. Reheat chicken, rice, and vegetables together; add sauce and fresh herbs when serving.",
  },
  {
    id: "seared-chicken-thighs-roasted-veg-22",
    number: 19,
    name: "Seared Chicken Thighs + Veggies",
    imageUrl: "/recipes/seared-chicken-thighs-veggies.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "meal_prep", "batch_friendly"],
    mealSlots: ["lunch", "dinner"],
    calories: 565,
    protein: 42,
    carbs: 32,
    fat: 30,
    prepMinutes: 15,
    cookMinutes: 30,
    servingWeightGrams: 505,
    ingredients: [
      { name: "Chicken thighs (bone-in, skin-on)", quantity: 2, unit: "medium", category: "Protein" },
      { name: "Olive oil", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Salt", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Black pepper", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Garlic powder", quantity: 0.25, unit: "tsp", category: "Spices" },
      { name: "Smoked paprika", quantity: 0.25, unit: "tsp", category: "Spices" },
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Pat thighs very dry — moisture prevents a crisp sear. Season all sides with salt, pepper, garlic powder, and paprika.",
      "Heat a cast-iron or stainless skillet over medium-high until a drop of water sizzles instantly. Add a thin coat of oil.",
      "Place thighs skin-side down and leave undisturbed 5–6 minutes until the skin is deep golden and releases easily from the pan.",
      "Flip and sear 3–4 minutes on the second side. If thighs are thick, transfer the skillet to the oven for 5–8 minutes until 165°F internal.",
      "Choose a vegetable variation below and roast on a sheet pan while you sear — both finish around the same time.",
      "Rest chicken 3–5 minutes before serving so juices stay in the meat.",
    ],
    variationDetails: searedChickenThighVariations,
    mealPrepNotes:
      "Refrigerate up to 4 days. Reheat chicken skin-side up in oven or air fryer to re-crisp; vegetables reheat in oven or microwave.",
  },
  {
    id: "sheet-pan-honey-garlic-chicken-broccoli-with-white-rice-06",
    number: 20,
    name: "Sheet Pan Chicken + Veggies",
    imageUrl: "/recipes/sheet-pan-chicken-veggies.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "meal_prep", "batch_friendly"],
    mealSlots: ["lunch", "dinner"],
    calories: 560,
    protein: 46,
    carbs: 52,
    fat: 15,
    prepMinutes: 12,
    cookMinutes: 28,
    servingWeightGrams: 520,
    ingredients: [
      { name: "Chicken breast (boneless)", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Olive oil", quantity: 1, unit: "tbsp", category: "Pantry" },
    ],
    instructions: [
      "Heat oven to 425°F (220°C).",
      "Choose a variation below for your vegetable mix and seasoning style.",
      "Toss vegetables with oil and seasonings on a sheet pan; add chicken and roast until chicken reaches 165°F.",
      "For rice variations, warm rice in the microwave while the pan roasts. For Greek Orzo, cook orzo per the variation before roasting.",
    ],
    variationDetails: sheetPanChickenVariations,
    mealPrepNotes:
      "Refrigerate up to 4 days. Reheat chicken and vegetables in oven or air fryer; add rice fresh if using a rice variation.",
  },
  {
    id: "teriyaki-turkey-rice-bowls-39",
    number: 22,
    name: "Teriyaki Turkey Rice Bowls",
    imageUrl: "/recipes/teriyaki-turkey-rice-bowls.png",
    cuisine: "asian",
    tags: ["whole_food", "high_protein", "meal_prep", "batch_friendly"],
    mealSlots: ["lunch", "dinner"],
    calories: 545,
    protein: 42,
    carbs: 58,
    fat: 15,
    prepMinutes: 15,
    cookMinutes: 15,
    ingredients: [
      { name: "Lean ground turkey", quantity: 6, unit: "oz", category: "Protein" },
      { name: "Cooked rice", quantity: 1, unit: "cup", category: "Grains" },
      { name: "Teriyaki sauce", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Green beans or broccoli", quantity: 1.5, unit: "cups", category: "Produce" },
      { name: "Sesame seeds (optional)", quantity: 1, unit: "tsp", category: "Pantry" }
    ],
    instructions: [
      "Brown turkey in a skillet and drain excess liquid if needed.",
      "Stir in teriyaki sauce and simmer 2–3 minutes.",
      "Portion with rice and vegetables; top with sesame seeds if using."
    ],
  },
  {
    id: "turkey-black-bean-chili-08",
    number: 23,
    name: "Turkey & Black Bean Chili",
    imageUrl: "/recipes/turkey-black-bean-chili.png",
    cuisine: "mexican",
    tags: ["whole_food", "high_protein", "meal_prep", "batch_friendly", "comfort"],
    mealSlots: ["lunch", "dinner"],
    calories: 455,
    protein: 35,
    carbs: 48,
    fat: 14,
    prepMinutes: 12,
    cookMinutes: 35,
    ingredients: [
      { name: "Lean ground turkey", quantity: 170, unit: "g", category: "Protein" },
      { name: "Black beans (canned, drained)", quantity: 1, unit: "cup", category: "Pantry" },
      { name: "Diced tomatoes (canned)", quantity: 14, unit: "oz", category: "Pantry" },
      { name: "Onion", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Bell pepper", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Chili powder", quantity: 1, unit: "tbsp", category: "Spices" },
      { name: "Cumin", quantity: 1, unit: "tsp", category: "Spices" }
    ],
    instructions: [
      "Sauté onion and pepper until soft.",
      "Add turkey; cook until browned.",
      "Stir in tomatoes, beans, and spices; simmer 25–30 minutes.",
      "Adjust salt to taste and serve."
    ],
  },
  {
    id: "turkey-hummus-wrap-12",
    number: 24,
    name: "Turkey + Veggie Hummus Wrap",
    imageUrl: "/recipes/turkey-veggie-hummus-wrap.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "meal_prep"],
    mealSlots: ["lunch"],
    calories: 475,
    protein: 43,
    carbs: 38,
    fat: 16,
    prepMinutes: 10,
    cookMinutes: 0,
    servingWeightGrams: 385,
    ingredients: [
      { name: "Whole wheat or spinach tortilla", quantity: 1, unit: "large", category: "Grains" },
      { name: "Sliced turkey", quantity: 5, unit: "oz", category: "Protein" },
      { name: "Hummus", quantity: 2, unit: "tbsp", category: "Pantry" },
      { name: "Mustard (optional)", quantity: 1, unit: "tsp", category: "Pantry" },
    ],
    instructions: [
      "Spread about 2 tbsp hummus thinly over the tortilla — enough to bind the filling without soaking the wrap.",
      "Layer sliced turkey evenly, leaving a small border at the edges.",
      "Choose a vegetable variation below and add those ingredients on top of the turkey.",
      "Optional: a thin line of mustard for extra tang.",
      "Fold in the sides, roll tightly from the bottom, and slice in half on the diagonal.",
      "Pack cut-side down in a container for meal prep; keeps 2–3 days refrigerated.",
    ],
    variationDetails: turkeyHummusWrapVariations,
    mealPrepNotes:
      "Keeps 2–3 days refrigerated wrapped in foil or a container. Pat veggies dry before rolling to prevent sogginess.",
  },
  {
    id: "turkey-burger-patty-salad-kit-19",
    number: 25,
    name: "Turkey Burger Bowl",
    imageUrl: "/recipes/turkey-burger-bowl.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "quick", "meal_prep"],
    mealSlots: ["lunch", "dinner"],
    calories: 485,
    protein: 40,
    carbs: 18,
    fat: 28,
    prepMinutes: 10,
    cookMinutes: 12,
    servingWeightGrams: 420,
    ingredients: [
      { name: "Turkey burger patty", quantity: 1, unit: "large", category: "Protein" },
      { name: "Romaine or mixed greens", quantity: 2, unit: "cups", category: "Produce" },
      { name: "Avocado (sliced)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Tomato (sliced)", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Red onion (thin slices)", quantity: 2, unit: "tbsp", category: "Produce" },
      { name: "Light chipotle mayo or burger sauce", quantity: 1.5, unit: "tbsp", category: "Pantry" },
      { name: "Sesame seeds (optional)", quantity: 1, unit: "tsp", category: "Pantry" },
    ],
    instructions: [
      "Grill or sear the turkey patty in a skillet or grill pan until cooked through (165°F), about 4–5 minutes per side.",
      "Chop romaine and add to a bowl as the base.",
      "Top with sliced tomato, red onion, and avocado in separate sections.",
      "Place the warm patty on the bowl and drizzle with chipotle mayo or burger sauce.",
      "Sprinkle sesame seeds over avocado if using; serve immediately or pack sauce separately for meal prep.",
    ],
    mealPrepNotes:
      "Keeps 2–3 days refrigerated. Pack patty and sauce separately; assemble bowl when eating so greens stay crisp.",
  },
  {
    id: "turkey-chili-18",
    number: 26,
    name: "Turkey Chili No Beans",
    imageUrl: "/recipes/turkey-chili-no-beans.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "batch_friendly", "meal_prep", "comfort"],
    mealSlots: ["lunch", "dinner"],
    calories: 430,
    protein: 40,
    carbs: 22,
    fat: 18,
    prepMinutes: 12,
    cookMinutes: 35,
    ingredients: [
      { name: "Lean ground turkey", quantity: 170, unit: "g", category: "Protein" },
      { name: "Diced tomatoes (canned)", quantity: 1.5, unit: "cups", category: "Pantry" },
      { name: "Bell pepper", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Onion", quantity: 0.5, unit: "medium", category: "Produce" },
      { name: "Olive oil", quantity: 1, unit: "tsp", category: "Pantry" },
      { name: "Mild chili seasoning", quantity: 1, unit: "tbsp", category: "Spices" },
      { name: "Cumin", quantity: 0.5, unit: "tsp", category: "Spices" }
    ],
    instructions: [
      "Heat oil in a pot; sauté onion and bell pepper until softened.",
      "Add ground turkey; cook until browned and crumbled.",
      "Stir in diced tomatoes and seasonings.",
      "Choose a variation below for extra vegetables if desired (macros update automatically).",
      "Simmer uncovered 25–30 minutes until thickened; salt to taste and portion.",
    ],
    variationDetails: [
      {
        id: "classic",
        label: "Classic (base veggies)",
        ingredients: [],
        instructions: ["Simmer until thickened and serve."],
      },
      {
        id: "extra-vegetables",
        label: "Extra vegetables",
        ingredients: [
          { name: "Zucchini or yellow squash (diced)", quantity: 1, unit: "cup", category: "Produce" },
          { name: "Carrots (diced)", quantity: 0.5, unit: "cup", category: "Produce" },
          { name: "Celery (diced)", quantity: 0.5, unit: "cup", category: "Produce" },
          { name: "Corn kernels", quantity: 0.5, unit: "cup", category: "Produce" },
        ],
        instructions: [
          "Add diced zucchini, carrots, and celery with the bell pepper.",
          "Stir in corn after the turkey is browned.",
          "Simmer until all vegetables are tender and the chili is thick.",
        ],
        calories: 505,
        protein: 42,
        carbs: 38,
        fat: 18,
      },
    ],
  },
  // Dinner
  {
    id: "baked-salmon-with-asparagus-sweet-potato-03",
    number: 27,
    name: "Baked Salmon with Asparagus & Sweet Potato",
    imageUrl: "/recipes/baked-salmon-asparagus-sweet-potato.png",
    cuisine: "american",
    tags: ["whole_food", "high_protein", "meal_prep"],
    mealSlots: ["dinner"],
    calories: 560,
    protein: 42,
    carbs: 38,
    fat: 26,
    prepMinutes: 12,
    cookMinutes: 22,
    ingredients: [
      { name: "Salmon fillet", quantity: 170, unit: "g", category: "Protein" },
      { name: "Asparagus", quantity: 12, unit: "spears", category: "Produce" },
      { name: "Sweet potato", quantity: 1, unit: "medium", category: "Produce" },
      { name: "Olive oil", quantity: 1, unit: "tbsp", category: "Pantry" },
      { name: "Garlic powder", quantity: 0.5, unit: "tsp", category: "Spices" },
      { name: "Salt", quantity: 0.25, unit: "tsp", category: "Spices" }
    ],
    instructions: [
      "Heat oven to 400°F (200°C).",
      "Cube sweet potato; toss with half the oil and roast 12 minutes.",
      "Add salmon and asparagus; drizzle remaining oil and seasonings.",
      "Bake 10–12 minutes until salmon flakes easily."
    ],
  },
  // Snack / beverages (selectable; not auto-generated)
  {
    id: "bev-milk",
    number: 36,
    name: "Milk",
    cuisine: "american",
    tags: ["beverage", "whole_food", "quick"],
    mealSlots: ["breakfast", "lunch", "dinner", "snack"],
    calories: 122,
    protein: 8,
    carbs: 12,
    fat: 5,
    fiber: 0,
    prepMinutes: 0,
    cookMinutes: 0,
    servingWeightGrams: 244,
    cookStyle: "assembled",
    ingredients: [
      { name: "Milk (2%)", quantity: 1, unit: "cup", category: "Dairy" },
    ],
    instructions: [
      "Pour 1 cup (8 fl oz) per adult serving. Child servings are smaller automatically.",
      "Serve cold.",
    ],
  },
  {
    id: "bev-fat-free-milk",
    number: 37,
    name: "Fat-free milk",
    cuisine: "american",
    tags: ["beverage", "whole_food", "quick"],
    mealSlots: ["breakfast", "lunch", "dinner", "snack"],
    calories: 83,
    protein: 8,
    carbs: 12,
    fat: 0,
    fiber: 0,
    prepMinutes: 0,
    cookMinutes: 0,
    servingWeightGrams: 245,
    cookStyle: "assembled",
    ingredients: [
      { name: "Fat-free milk", quantity: 1, unit: "cup", category: "Dairy" },
    ],
    instructions: [
      "Pour 1 cup (8 fl oz) per adult serving. Child servings are smaller automatically.",
      "Serve cold.",
    ],
  },
  {
    id: "bev-sweetened-drink",
    number: 38,
    name: "Sweetened drink",
    cuisine: "american",
    tags: ["beverage", "quick"],
    mealSlots: ["breakfast", "lunch", "dinner", "snack"],
    calories: 140,
    protein: 0,
    carbs: 39,
    fat: 0,
    fiber: 0,
    prepMinutes: 0,
    cookMinutes: 0,
    servingWeightGrams: 355,
    cookStyle: "assembled",
    ingredients: [
      { name: "Sweetened drink (soda, juice, or similar)", quantity: 12, unit: "fl oz", category: "Pantry" },
    ],
    instructions: [
      "One 12 fl oz serving per adult. Child servings are smaller automatically.",
      "Generic sugar-sweetened beverage — use soda, juice, or a similar sweetened drink.",
    ],
  },
];
